### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by andrewknockin** [porrey/EEPROM-Storage#1]
Thank you very much for this excellent storage code which I have just found, and especially for the well explained and really detailed description in README.md.
On reading README.md, can I suggest:
1) the second paragraph has a repeated word 'in' "...a variable can be used in in the same..."
2) in the second example code in Overview, line 2 includes "a default value of 0 at EEPROM address 0". A user reading this for the first time has no way of knowing which of 'EEPROMStorage<int> i(0, 0)' is the default and which the address - it isn't explained until almost the end of the whole README.md. If instead a default value of 255 was written at 0, it would be immediately obvious 'EEPROMStorage<int> i(0, 255)'. This is what really caused this feedback.
3) the Tips are actually important recommendations, so  "The following are suggestions and not necessary things you must avoid" could be positively promoted as "The following are recommendations"
4) the final line in Tips "I recommend if you must do any of these above, test them first" would be difficult to implement. Its basically suggesting that the write is repeated to destruction to determine the true limit, possibly resulting in a damaged board. The line could be omitted.
5) in EEPROM Storage Initialization, it states "The first tme a value is written" with a missing 'i' in time.
6) in Scope it states "This behavoir can" instead of 'behavior'

**Comment by porrey** [comment]
Thanks, I''ll take a look when I get a chance, however, feel free to do a pull request and update the read me.

**Comment by porrey** [comment]
Corrections applied. Used 10 instead of 255 for example.

**Comment by andrewknockin** [comment]
Thanks. Is it possible for me to delete that post now?
